import { BarChart } from "@mui/x-charts/BarChart";
import { useAppStore } from "../store";
import { chapterById, loadCourseCatalog } from "../courseCatalog";
import { Sidebar } from "../components/Sidebar";
import { StudentAnnouncements } from "../components/StudentAnnouncements";
import { StatCard } from "../components/StatCard";
import { FirstTimeWelcome } from "../FirstTimeWelcome";
import { CountUp, FadeContent } from "../ui-react-bits";
import { chapterProgress, moduleStats } from "../utils/progressHelpers";
import { moduleAbbrev } from "../utils/moduleAbbrev";
export { StatCard, StudentAnnouncements };
